### ISSUE TITLE
Implement logic to find more than one package.json

### ISSUE THREAD

**Issue by NightLore** [NightLore/DependencyVis#10]

**Comment by NightLore** [comment]
Add logic to allow user to input a specific folder to search (or narrow down search in some way)

**Comment by bcdasilv** [comment]
Also, take at look at [package-lock.json](https://docs.npmjs.com/configuring-npm/package-lock-json.html) or [here](https://medium.com/@dltlabs/package-json-vs-package-lock-json-c8d5deba12cb)
